spring:
  application:
    name: git-guru-gateway
  config:
    import: classpath:base.yml,classpath:config.yml # classpath:cache.yml classpath:limiter.yml
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'
      routes:
        - id: git-guru-auth
          uri: lb://git-guru-auth
          predicates:
            - Path=/auth/**,/token/**
        - id: git-guru-service
          uri: lb://git-guru-service
          predicates:
            - Path=/trade/**,/order/**,/user/**,/collection/**,/wxPay/**,/box/**
server:
  port: 8081
