spring:
  application:
    name: git-guru-business
  datasource:
    url: jdbc:mysql://localhost:3306/gitguru?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: classpath:cache.yml
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max-latest



server:
  port: 8083
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.alibaba.cloud.ai: debug
    com.donnan.git.guru.business: debug
github:
  client:
    token: ${GITHUB_TOKEN}
    user:
      max:
        num: 9930000
    thread:
      num: 10


