spring:
  application:
    name: git-guru-business
  config:
    import: classpath:base.yml,classpath:cache.yml
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: deepseek-v3



server:
  port: 8083
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.alibaba.cloud.ai: debug
    com.donnan.git.guru.business: debug
github:
  client:
    token: ${GITHUB_TOKEN}
    user:
      max:
        num: 9930000
    thread:
      num: 10


